source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GoogleImageSearch_Example', :exclusive => true do
  pod 'GoogleImageSearch', :path => '../'
end

target 'GoogleImageSearch_Tests', :exclusive => true do
  pod 'GoogleImageSearch', :path => '../'

  
end
